### ISSUE TITLE
Quick Start nor website load in Edge

### ISSUE THREAD

**Issue by joe-vella** [Teradata/covalent-quickstart#16]
This repository's issues are reserved for feature requests and bug reports.
### Do you want to request a _feature_ or report a _bug_?

Bug
#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/
#### Bug Report

please provide steps to reproduce and if possible screenhots or animated Gifs.
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/

Using Edge on Win 10 navigate to https://teradata.github.io/covalent/#/
  It hangs on the logo in the middle of the screen.

Same thing for the Quick Start project (http://localhost:4200/#/). Error from Edge dev tools below. 

```
SCRIPT65535: Argument not optional 
main.bundle.js (154028,13)
```

Note: Both urls work fine in Chrome and Firefox on the same machine. 
#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
##### Other information

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by kyleledbetter** [comment]
Covalent & Quickstart both work in Edge now
