### ISSUE TITLE
Remove loading Quickstart

### ISSUE THREAD

**Issue by QuantumRich** [Teradata/covalent-quickstart#17]
Big fan of this; using it to prototype much faster.

Is it possible to remove the "Loading Covalent Quickstart" screen that occurs every time I refresh?  It would rapidly increase my development time.

**Comment by kyleledbetter** [comment]
glad to hear it!
to customize the loading message (which must show for angular 2 apps currently), edit these lines: https://github.com/Teradata/covalent-quickstart/blob/develop/src/index.html#L12-L15

**Comment by QuantumRich** [comment]
So the 2 seconds or so that the loading message uses will always be there?

**Comment by kyleledbetter** [comment]
Yup on first load or reload

**Comment by emoralesb05** [comment]
Thats actually not covalent. 

Its the time it takes between the code files loading and the angular2 compiler doing its magic to render everything.

**Comment by QuantumRich** [comment]
Ah, I see!  I guess there's no trick where I can just edit a few words in my code and not have to wait the two seconds then.  Thanks.

**Comment by kyleledbetter** [comment]
closing since this is an angular2 thing
