### ISSUE TITLE
there is a issue with template label does not actually let you change  quite quickly it takes time or label does not open until next button is clicked  

### ISSUE THREAD

**Issue by saketh1991** [Teradata/covalent-quickstart#22]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

please provide steps to reproduce and if possible screenhots or animated Gifs.
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by emoralesb05** [comment]
Hey man,
template label of what?? what exactly are you trying to do? 

Also, please give code examples and more info regarding an issue or doubt.
