### ISSUE TITLE
typo in app module preventing app from running

### ISSUE THREAD

**Issue by Mark-McCracken** [Teradata/covalent-quickstart#30]
#### Bug Report

CovalentHttpModule.forRoot({
      inteceptors: [{
        interceptor: RequestInterceptor, paths: ['**'],
      }],
    }),

inteceptors should be interceptors

**Comment by kyleledbetter** [comment]
Hi and thanks for reporting. We have a PR with that fix in progress just not merged yet https://github.com/Teradata/covalent-quickstart/pull/29

You'll also want to make sure you update the Covalent packages to 0.10.2 instead of 0.10.0 bc there were a couple of hotfixes

**Comment by Mark-McCracken** [comment]
Ah! Sorry about that, should've checked.
Yeah got the latest version, all seems to work well, this is a nice example project! Very useful.

**Comment by kyleledbetter** [comment]
sry about that confusion @Mark-McCracken closing since fix is merged in quickstart, and beta1 quickstart is out! :)

**Comment by Mark-McCracken** [comment]
Thanks! Excited to try this new version, looks really solid and very up to date, appreciate the efforts man!
