### ISSUE TITLE
NG serve - stop at webpack: compiled succesfully

### ISSUE THREAD

**Issue by roselykm** [Teradata/covalent-quickstart#39]
Follow exactly the setup instructions.

OS: Windows 7 - 64 bit
node -v: 6.9.4
npm -v: 4.1.1
![screenshot 2017-02-12 17 31 36](https://cloud.githubusercontent.com/assets/6478866/22861016/35627764-f149-11e6-90b6-9f059723c4d2.png)

**Comment by emoralesb05** [comment]
Not sure i understand the problem. What were you expecting to see when you executed `ng serve`?

Go to your browser and open `localhost:4200`

**Comment by roselykm** [comment]
Haha sorry, my bad. Im used to code using browserify and gulp and it always open the browser for me lol, automatically. Also Im use to using node server where it always said that server is running at localhost:XXXX after compiling and bundle build.

**Comment by kyleledbetter** [comment]
some versions weren't showing that for the cli but the latest (1.0.0-beta-31) shows

`** NG Live Development Server is running on http://localhost:4200. **`
