### ISSUE TITLE
angular-cli webpack branch support

### ISSUE THREAD

**Issue by tapas4java** [Teradata/covalent-quickstart#4]
Any chance to test with `angular-cli`webpack branch which is landing in master this week?

**Comment by kyleledbetter** [comment]
Once there's a release we'll pull it in

**Comment by emoralesb05** [comment]
Hey @tapas4java, We only update to `angular-cli` npm releases. Once the `webpack` branch gets merged and released we will update and start testing it, which should be soon.

**Comment by tapas4java** [comment]
Thanks @kyleledbetter and @emoralesb05 .

**Comment by duxy2002** [comment]
where is the webpack branch?
