### ISSUE TITLE
Bug: Use behind corporate proxy

### ISSUE THREAD

**Issue by natejgardner** [Teradata/covalent-quickstart#43]
When following the getting started instructions from behind a corporate proxy, the command `webdriver-manager update` fails. Simply adding args `--proxy=<proxy>` and `--ignore_ssl` does not help.

**Comment by emoralesb05** [comment]
Thats a selenium issue. 

We just point out the steps you need to do to set it up (e2e), but the issues surrounding that belong to https://github.com/angular/webdriver-manager

**Comment by emoralesb05** [comment]
Also, its not needed to run covalent.

Its just a setup for the `e2e` test suite.
