### ISSUE TITLE
Kindly Update angular-cli to Latest

### ISSUE THREAD

**Issue by totalard** [Teradata/covalent-quickstart#45]
The Version you specified is depreciated.

If i update it mannually.. i getting Error

Ng Serv not working.. It need both global and local should be same.. So make your angular-cli latest

**Comment by kyleledbetter** [comment]
Yup we just updated Covalent itself to the latest. Takes us a couple days to update quickstart. Accepting PRs if you'd like to help :)

**Comment by kyleledbetter** [comment]
updated in https://github.com/Teradata/covalent-quickstart/pull/46
