### ISSUE TITLE
Replace '~@' with relative path in .scss files.

### ISSUE THREAD

**Issue by ElderJames** [Teradata/covalent-quickstart#53]
Hi!
I got a problem when I build the covalent with webpack like below:

> File to import not found or unreadable: ~@angular/material/core/theming/all-theme.
   
And when I replace '~' with '../node_modules/@angular/material/core/theming/all-theme' ,it changed to  print the error with covalent's theme files.

So is there anyone can help?

**Comment by emoralesb05** [comment]
Since you are using webpack, you can leverage the loader `sass-loader` so it recognizes what `~` means.

Also, you can do this https://github.com/Teradata/covalent/issues/450#issuecomment-289589117

**Comment by ElderJames** [comment]
Thanks!
But I had used sass-loader in the webpack configuration file but it didn't work...

```
       {
               test: /\.scss$/,
               use: ['raw-loader', 'css-loader', 'sass-loader']
        },
```

**Comment by kombadzomba** [comment]
I've forked current master (1.0.0-beta.2) and replaced ~ with relative references. You may use @enelit/covalent-core instead of @covalent/core until this bug is fixed. 
[Here](https://www.npmjs.com/package/@enelit/covalent-core) are the npm package details.
Enjoy!

**Comment by emoralesb05** [comment]
This was fixed in `beta.3-1`. 😄
