### ISSUE TITLE
ERROR in Cannot read property 'getSymbolByModule' of undefined

### ISSUE THREAD

**Issue by enzonotario** [Teradata/covalent-quickstart#58]
Hi!

### Do you want to request a *feature* or report a *bug*?

Report a bug

#### Bug Report

I cloned this repo and do all the stuff.. when I run "ng serve", it shows me an error and doesn't compile:
```ERROR in Cannot read property 'getSymbolByModule' of undefined```

I searched in google and adding this line to ```tsconfig.app.json```:
```"files": ["main"],```, below of "compileOnSave", and it works...

Do you know if it is right to add this line? maybe you forgotten to add that line? or I'm wrong?

Thanks!

**Comment by emoralesb05** [comment]
Cant really replicate the error, can you give us more info about your env?

**Comment by enzonotario** [comment]
Well the cli -v shows me that:
```
@angular/cli: 1.0.0
node: 6.10.0
os: linux x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/flex-layout: 2.0.0-beta.7
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/platform-server: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
```

Maybe it's only my problem. I don't know why... but, at the end, it works adding that line. I only submit this issue thinking that maybe you forgotten to add that line, or to know if I must not add that line and have to check other thing of my env...

**Comment by emoralesb05** [comment]
Yeah not sure either, but `files` only tell the compiler which items to include in its compilation (which `main.ts` is the entry point). So that should be fine if that works for you.

**Comment by enzonotario** [comment]
ok, thanks so much!

**Comment by aervin** [comment]
As a follow up--

Adding `"files": ["main"]` to tsconfig solved this problem for me as well. 

While dealing w/ this issue, I noticed the CLI was serving up my main/vendor/inline/etc bundles, but not my lazy-loaded modules. After adding `"files": ["main"]` to tsconfig, lazy-loaded "chunks" are compiled like normal. Leads me to believe this may be an issue with lazy-loaded modules and the compiler? Just thought I'd share.
