### ISSUE TITLE
Feature - Collapsible Sidenav and Navlist Items

### ISSUE THREAD

**Issue by bengwall** [Teradata/covalent-quickstart#62]
#### Feature Request

Adding collapsible Sidenav and Navlists items.  This would allow for options to organize these when used as menus.

Here's a live [example](https://fury.martinsuess.com)

![screen shot 2017-05-17 at 10 51 23 am](https://cloud.githubusercontent.com/assets/4481748/26163399/3af09dec-3aef-11e7-86b9-c0949071aedb.png)

**Comment by kyleledbetter** [comment]
hi, sounds like a Covalent platform request for the Layout components https://github.com/Teradata/covalent/issues

The sidenav is already collapsible, but to add more options we already have this open feature request https://github.com/Teradata/covalent/issues/530

Now, for the collapsible nav list items with children that sounds like a separate feature request, can you open a new feature request with this info there?

**Comment by bengwall** [comment]
You are right.  I need to enter this over there.  I'll go ahead and do that.
