### ISSUE TITLE
CovalentCoreModule not available

### ISSUE THREAD

**Issue by ranouf** [Teradata/covalent-quickstart#63]
Hi,

My app is based on : npm install -g yo generator-aspnetcore-spa

Then I removed Bootstrap and now I try to install Angular Material + Covalent

This is my packages.json

>  "name": "WebApplicationBasic",
>   "version": "0.0.0",
>   "scripts": {
>     "test": "karma start ClientApp/test/karma.conf.js"
>   },
>   "dependencies": {
>     "@angular/animations": "^4.0.0",
>     "@angular/common": "^4.0.0",
>     "@angular/compiler": "^4.0.0",
>     "@angular/core": "^4.0.0",
>     "@angular/forms": "^4.0.0",
>     "@angular/http": "^4.0.0",
>     "@angular/material": "2.0.0-beta.5",
>     "@angular/platform-browser": "^4.0.0",
>     "@angular/platform-browser-dynamic": "^4.0.0",
>     "@angular/platform-server": "^4.0.0",
>     "@angular/router": "^4.0.0",
>     "@covalent/core": "1.0.0-beta.4",
>     "@types/node": "7.0.18",
>     "angular2-template-loader": "0.6.2",
>     "aspnet-prerendering": "^2.0.5",
>     "aspnet-webpack": "^1.0.29",
>     "awesome-typescript-loader": "3.1.3",
>     "css": "2.2.1",
>     "css-loader": "0.28.1",
>     "es6-shim": "0.35.3",
>     "event-source-polyfill": "0.0.9",
>     "expose-loader": "0.7.3",
>     "extract-text-webpack-plugin": "2.1.0",
>     "file-loader": "0.11.1",
>     "html-loader": "0.4.5",
>     "isomorphic-fetch": "2.2.1",
>     "jquery": "3.2.1",
>     "json-loader": "0.5.4",
>     "preboot": "4.5.2",
>     "reflect-metadata": "0.1.10",
>     "rxjs": "^5.0.1",
>     "style-loader": "0.17.0",
>     "to-string-loader": "1.1.5",
>     "typescript": "2.3.2",
>     "url-loader": "0.5.8",
>     "webpack": "2.5.1",
>     "webpack-hot-middleware": "2.18.0",
>     "webpack-merge": "4.1.0",
>     "zone.js": "^0.8.4",
>     "raw-loader": "^0.5.1",
>     "sass-loader": "^6.0.5"
>   },
>   "devDependencies": {
>     "@types/chai": "3.5.2",
>     "@types/jasmine": "2.5.47",
>     "chai": "3.5.0",
>     "jasmine-core": "2.6.1",
>     "karma": "1.7.0",
>     "karma-chai": "0.1.0",
>     "karma-chrome-launcher": "2.1.1",
>     "karma-cli": "1.0.1",
>     "karma-jasmine": "1.1.0",
>     "karma-webpack": "2.0.3",
>     "node-sass": "^4.5.3"
>   }
> }
> 

In app.module.client, I added:
import { MaterialModule } from '@angular/material';
import {
    CovalentCoreModule
} from '@covalent/core';

@NgModule({
    bootstrap: sharedConfig.bootstrap,
    declarations: sharedConfig.declarations,
    imports: [
        //...
        CovalentCoreModule.forRoot(),
        //...

        ...sharedConfig.imports
    ],
    providers: [
        { provide: 'ORIGIN_URL', useValue: location.origin }
    ]
})
export class AppModule {
}

CovalentCoreModule is not available anymore, what is the workaround to make it work?

I tried by adding all the module available:
        CovalentChipsModule,
        CovalentCommonModule,
        CovalentDataTableModule,
        CovalentDialogsModule,
        CovalentExpansionPanelModule,
        CovalentFileModule,
        CovalentJsonFormatterModule,
        CovalentLayoutModule,
        CovalentLoadingModule,
        CovalentMediaModule,
        CovalentMenuModule,
        CovalentMessageModule,
        CovalentNotificationsModule,
        CovalentPagingModule,
        CovalentSearchModule,
        CovalentStepsModule,

But I still have an error:
If 'md-card-content' is an Angular component, then verify that it is part of this module.

What do you suggest?

**Comment by emoralesb05** [comment]
`md-card` is a material component. https://material.angular.io/components 

You need to import their modules also.

**Comment by ranouf** [comment]
Thanks.
app.module.client:
import {
    MaterialModule,
    MdCardModule
} from '@angular/material';

imports: [
        MaterialModule,
        MdCardModule,
]

Still the same error:
If 'md-card-content' is an Angular component, then verify that it is part of this module.

Do you have an idea

**Comment by jotatoledo** [comment]
is the issue solved? @ranouf

**Comment by ranouf** [comment]
Yes, but I dont remember how I did it. sorry for the next one who will need ans answer :(

**Comment by netbka** [comment]
Having same issue in my package.json I have 
"@angular/material": "^2.0.0-beta.6",
and I am getting on npm i unmet error:
UNMET PEER DEPENDENCY @angular/material@2.0.0-beta.6
+-- @covalent/dynamic-forms@1.0.0-beta.4
| `-- UNMET PEER DEPENDENCY @angular/material@2.0.0-beta.5
+-- @covalent/highlight@1.0.0-beta.4
