### ISSUE TITLE
RTL layout issue

### ISSUE THREAD

**Issue by mmdsharifi** [Teradata/covalent-quickstart#65]
This repository's issues are reserved for feature requests and bug reports.

#### Bug Report

please provide steps to reproduce and if possible screenhots or animated Gifs.
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/
![screencapture-localhost-4200-logs-1496418216001](https://cloud.githubusercontent.com/assets/6915384/26733654/bc3b0534-47d0-11e7-87ae-7846b3dba9e1.png)

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
```
Windows 10
node v6.9.5
npm 3.10.10
@covalent/core 1.0.0-beta.3
```

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by jotatoledo** [comment]
not sure if that feature was active on the quickstart repo.
Could you tell me where should I add `dir="rtl"` to test this locally? :smile:

**Comment by mmdsharifi** [comment]
Thanks for your replay, first.

You can add `dir="rtl"` in `src/index.html` file. I founded a way to fix it, by overriding the inline styles:
```
ngAfterViewChecked () {
    let sidenav = document.getElementsByClassName('mat-sidenav-content');
    sidenav[1].style.marginLeft = "0px"
    sidenav[1].style.marginRight = "300px"
  }
```
but, you know this is not good solution, any better one ?

**Comment by jotatoledo** [comment]
there is a similar function implemented on the documentation page of covalent, maybe you could take a look in the source code and take some ideas from that

**Comment by emoralesb05** [comment]
Yeah, you need to do something like this

```
  constructor(private _dir: Dir) {
    this._dir.dir = 'rtl';
  }
```

Since `Dir` is an `angular/material` service that is used in the sidenavs

**Comment by mmdsharifi** [comment]
Thanks @emoralesb05 , It works.
