### ISSUE TITLE
CovalentCoreModule not available 

### ISSUE THREAD

**Issue by netbka** [Teradata/covalent-quickstart#67]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Report a Bug

#### Bug Report
After installing yo aspnetgenerator-spa I am trying to add CovalentCoreModule.
But getting unmet error:
UNMET PEER DEPENDENCY @angular/material@2.0.0-beta.6
+-- @covalent/dynamic-forms@1.0.0-beta.4
| `-- UNMET PEER DEPENDENCY @angular/material@2.0.0-beta.5
+-- @covalent/highlight@1.0.0-beta.4

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
My dependencies are:
 "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/compiler-cli": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/platform-server": "^4.1.3",
    "@angular/router": "^4.1.3",
		"@covalent/core": "1.0.0-beta.4",
    "@covalent/dynamic-forms": "1.0.0-beta.4",
    "@covalent/highlight": "1.0.0-beta.4",
    "@covalent/http": "1.0.0-beta.4",
    "@covalent/markdown": "1.0.0-beta.4",
    "@types/node": "7.0.18",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^2.0.5",
    "aspnet-webpack": "^1.0.29",
    "awesome-typescript-loader": "3.1.3",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.1",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.1",
    "hammerjs": "^2.0.8",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "less": "^2.7.2",
    "less-loader": "^4.0.4",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.0",
    "style-loader": "0.17.0",
    "to-string-loader": "1.1.5",
    "typescript": "^2.3.4",
    "url-loader": "0.5.8",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.0",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.10"
  },

Please help me with installing CovalentCoreModule.
Thank you

**Comment by jotatoledo** [comment]
You need material beta.5. The `CovalentCoreModule` was **removed** in the beta.4 release. Since then developers have to import the modules that they need individually. In the [docs ](https://teradata.github.io/covalent/#/)there is more information related to this topic.

**Comment by netbka** [comment]
I looked at your package.json file 
you have "@angular/material": "2.0.0-beta.6",
so do I (I made the change and remove the ^)
but still getting the same error.

**Comment by jotatoledo** [comment]
Yea the dependency for material was incorrect. This was fixed a couple of hours ago. Run `npm install --save @angular/material@2.0.0-beta,5` to install the correct version of material

**Comment by netbka** [comment]
Thank you.
That worked!

**Comment by jotatoledo** [comment]
No worries :ok_hand:, consider closing the issue if solved
