### ISSUE TITLE
How to bind java or any backend to this example?

### ISSUE THREAD

**Issue by gkhakare** [Teradata/covalent-quickstart#7]
I am trying to start writing an application with covalent-quickstart as starting point. 
But when I tries to get data from java rest api, i get an error of cross origin access.

**Comment by emoralesb05** [comment]
hey @gkhakare 
Angular in general needs you to enable CORS in the java rest api by adding a header. You can find lots of examples if you google it. Here are a few examples i found online:

https://htet101.wordpress.com/2014/01/22/cors-with-angularjs-and-spring-rest/
http://www.codingpedia.org/ama/how-to-add-cors-support-on-the-server-side-in-java-with-jersey/

**Comment by gkhakare** [comment]
Thank You @emoralesb05 for the reply.
Such headers has to be set by server who is serving browser request for getting html, javascript etc...
In our case it is angular-cli. We are running dev ui server using command "ng serve".
I am not able to get exact place where to set these headers..
Some of the forum asked to install add on using command "ng install ember-cli-cors". Ref: https://github.com/angular/angular-cli/issues/803
But it is giving an error: Error: The package @angular/forms@0.2.0 does not satisfy its siblings' peerDependencies requirements!
