### ISSUE TITLE
Custom created pages not rendered on Firefox and Safari?

### ISSUE THREAD

**Issue by jeck7** [Teradata/covalent-quickstart#78]
Hello ,

I have successfully used covalent-quickstart for prototyping this site:

https://mobilskys-events.tk

 ,but the pages which I have added are not rendered in Firefox and Safari , in Chrome everything   works fine ! Really to say the rest of the demo pages are rendered  correctly and I'm wondering where is my mistake, If someone could help will be great!

Reggards

**Comment by aciccarello** [comment]
@jeck7 Do you have a repo where someone could look at your work?

**Comment by aciccarello** [comment]
Also, I'd suggest using the [gitter channel](https://gitter.im/Teradata/covalent) for this type of support question since it is not an issue with the repo.

**Comment by jeck7** [comment]
Hello aciccarello,

Have you checked that is not  visible ? No it's a custom work sorry .

**Comment by jeck7** [comment]
Sorry and thanks !

**Comment by aciccarello** [comment]
I saw the issue on your website but it's hard to debug without the source.

**Comment by jeck7** [comment]
Actually there is no one error in the console (firefox and safary), that is the problem :)!
