### ISSUE TITLE
Custom Theme Documentation?

### ISSUE THREAD

**Issue by manndave** [Teradata/covalent-quickstart#81]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Feature Request...(documentation)

#### Feature Request

Please add an example of using the custom themes to the docs.  I can't for the life of me get them to work...

#### What is the expected behavior?
Top bar will change color to match the custom theme specs

##### Other information

I see the custom theme definitions in theme.scss but can't get them to be reflected in the UI following the latest guidance from the Angular Material project...i.e adding a wrapping div with `class='white-orange'`, for example.

**Comment by kyleledbetter** [comment]
Check out my tutorial https://medium.com/covalent-ui/angular-material-2-theme-tutorial-2f7e6c344006

**Comment by manndave** [comment]
Thanks for the quick response @kyleledbetter .  I should have mentioned that I'm trying to create a theme-switcher, so I need to have it working off of a class name using a conditional ngClass and a variable I can change to switch the theme that gets applied.  I've seen code for this using just straight Angular Material, and can actually get it working in Covalent for things like buttons (here: https://alligator.io/angular/angular-material-custom-theme/), but not for the top-bar using your layouts.  That *always* seems to be the primary or accent color of the default theme.
An example of what I need is in this video from Angular Connect: https://youtu.be/0q9FOeEELPY?t=1127, starting at 18:45 and about 3 minutes long.  It shows them changing a variable value and having it switch the theme.

Any ideas?  Thanks...

**Comment by kyleledbetter** [comment]
Yup we do this quite often. Just apply your custom theme class to your main component so it will wrap the custom theme around everything

**Comment by manndave** [comment]
Hmmm...OK, got it working in the Quickstart.  Now trying to move back to my codebase.  As a first step, I took the "Basic Demo" sample code from here: https://teradata.github.io/covalent/#/layouts/nav-view (which is the starting point for my page) and made that my entire app.component.html.  Built and loaded fine, except that the header bar is purple, not the black/grey shown on the demo page.  Changing my theme file has no effect - header is *always* purple.  
FWIW, this is my theme file:
```
@import '~@angular/material/_theming.scss';
@import '~@covalent/core/theming/all-theme';

@include mat-core();

$primary: mat-palette($mat-orange);
$accent: mat-palette($mat-green);

$theme: mat-light-theme($primary, $accent);

@include angular-material-theme($theme);
@include covalent-theme($theme);

.darkTheme {
  $dark-p: mat-palette($mat-green, 700);
  $dark-a: mat-palette($mat-pink);

  $dark-t: mat-dark-theme($dark-p, $dark-a);

  @include angular-material-theme($dark-t);
  @include covalent-theme($dark-t);
}
```
No purple or even blue palettes in sight.  (No, those aren't my real colors :-)  ).  I don't even get to the point of testing my darkTheme, as the header doesn't follow even the default theme.

I'm obviously doing something wrong, but I have no clue what.  Any pointers?

Thanks.

**Comment by manndave** [comment]
**Sigh**  Problem was a classic one-D, Ten-T (**1D10T**) error on my part...

Somewhere in all of my gyrations of trying to make things work, I added a reference to the material _deeppurple-amber_ theme in my style.scss and then never removed it.  That was the source of the purple header.  Combine that with a typo in the reference to my theme file and it caused all of the problems.

So, working now, thanks for the help.  I'm going back to beat my head against the wall now...

**Comment by istvanszoboszlai** [comment]
Just for reference: the approach described in the version 9.2.4 of angular material documentation did not work for me. 

Adding the dart-theme in the main module of my app with `overlayContainer.getContainerElement().classList.add('unicorn-dark-theme');` (as described in the documentation)  **did nothing**.

The approach, however, that is described here:
https://medium.com/@PhilippKief/automatic-dark-mode-detection-in-angular-material-8342917885a0
works flawlessly and is a lot more elegant IMHO.
