### ISSUE TITLE
BUG: Top left toolbar toggle button missing after upgrading to material beta 8 and covalent beta 6.

### ISSUE THREAD

**Issue by jic900** [Teradata/covalent-quickstart#82]
Easy steps to reproduce:
---------------------------
 It's running fine with the existing develop branch (Aug 19), I can see the toggle button on the top left of the top toolbar. However, after I upgraded to latest version (see below), the toggle button is missing.

1. Updated @angular/material to "2.0.0-beta.8"
2. Added "@angular/cdk": "2.0.0-beta.8"
3. Updated all @covalent packages to "1.0.0-beta.6"

![image](https://user-images.githubusercontent.com/24816552/29491690-c91a6fba-851f-11e7-8b9c-c57f03aa5536.png)

Qing

**Comment by kyleledbetter** [comment]
Check out the latest docs. You have to explicitly include the button https://teradata.github.io/covalent/#/layouts

**Comment by jic900** [comment]
Thanks a lot kyleledbetter. It's working now. That actually provides more flexibility to developers when they want to show/hide the button, like based on the screen size.

Qing
