### ISSUE TITLE
SVG in Firefox are oversized

### ISSUE THREAD

**Issue by pmullot** [Teradata/covalent-quickstart#87]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
BUG

#### Bug Report
svg icons are oversized in Firefox vs Chrome. 
To check by yourself, go to official Teradata Covalent Template Plnker for [Landing page app Template](https://teradata.github.io/covalent/#/templates) : https://run.plnkr.co/preview/cj81wh64u0007345sb154egxq/

##### Screenshots or link to CodePen/Plunker/JSfiddle
Chrome Screenshot: 
![chrome](https://user-images.githubusercontent.com/75703/30875801-f47f71d0-a2f4-11e7-9c30-c42b52d97927.png)

Firefox Screenshot
![firefox](https://user-images.githubusercontent.com/75703/30875815-fd5f0a40-a2f4-11e7-955f-eb61ff242e91.png)

#### What is the expected behavior?
svg rendering should be homogeneous across browsers. Chrome seems to render the svg in a corerct way, whereas Firefox doesn't

#### What is the motivation / use case for changing the behavior?
Web page design is distorted in Firexfox.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
**angular/cli:** 1.4.1
**node:** 7.10.1

**FireFox:**
55.0.2 (64-bit)

**Chrome:**
Version 61.0.3163.100 (Official Build) (64-bit)

**OS:**
Linux Mint 17 Qiana 
RELEASE=17
CODENAME=qiana
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17 Qiana"
DESKTOP=Gnome
TOOLKIT=GTK

##### Did this work in previous versions of Angular / Material?
Don't know

**Comment by kyleledbetter** [comment]
This is probably related to a similar flex height/width auto issue we saw in IE11. Our recommended fix is to actually set height and width in % or px: https://github.com/Teradata/covalent/blob/develop/docs/IE11.md#heightauto-probably-wont-work-on-flex-items

**Comment by pmullot** [comment]
Unfortunately, I have no time to investigate the causes.
I ended setting icons height & width by css, as recomended by @kyleledbetter
